pages:
  image: alpine:latest
  only:
    - main
  environment:
    name: production
    url: https://fikrirnurhidayat.gitlab.io
  script:
    - apk update
    - apk add emacs-nox git
    - ./bin/build
    - git submodule init
    - mv dist public
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ./packages
  artifacts:
    paths:
      - public
