#+title: About This Site
#+subtitle: Site that I build since 2021 and still has no proper functionality.
#+description: Site that I build since 2021 and still has no proper functionality.
#+author: Fikri Rahmat Nurhidayat
#+email: fikrirnurhidayat@gmail.com
#+date: 16 November 2022

I am a former programmer from [[https://binaracademy.com][Binar Academy]], an edutech company. As an employee who cares about company's vision, I love to share my knowledge, experience, and whatever I know, either it's on technology field, or other field of expertise.

Because of that, I want to build this site. This site will be my vessel to share my knowledge, experience, and my point of view about this world. I believe that by sharing whatever I have, I indirectly contribute to make better education, and help this world to progress to be better in healthy common sense.

Every content on this site is all my work. Of course, I'll cite every information that I learn from other people, nobody starts from scratch.

* Content on This Sites

This site will contain my writing about the following topics:
- Computer
- GNU/Linux
- Free and Open Source Software
- Programming
- Emacs
- etc.

I happen to know about those topics, and I really love it as well. There's a lot of stuff that can be talked about, written about those topics. Take emacs as example, I wrote this website just using emacs, this writing is also written in emacs with =.org= as format. This writing then converted into HTML by emacs. I can even export this writing as PDF.

I hope that you catch the outline of what I'm going to write in the future.

* How Often Will I Write?

Honestly, I don't know. I'm an amateur writer. I love writing, but that doesn't necessarily mean that I can write a lot, since I have another issue that I need to face. It's laziness.

I'll try to write every month, but I can't promise. Even, I have a tedency to delete my writing when I think it was not good enough, just like all of my writing ont this website.

* What Built This Website

Just as I said upfront, this website was built using emacs. I use [[https://simplecss.org/][Simple.css]] for the UI, but that can be changed in the future.
